#!/usr/bin/env bash
# post-create.sh — runs once after the Dev Container is created.
# Works identically in VS Code local Dev Containers and GitHub Codespaces.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND_DIR="$REPO_ROOT/src/chat-app/backend"
FRONTEND_DIR="$REPO_ROOT/src/chat-app/frontend"
ENV_FILE="$BACKEND_DIR/.env"

echo "==> Installing Python dependencies..."
pip install --progress-bar=off -r "$BACKEND_DIR/requirements.txt"

echo "==> Installing Node dependencies..."
npm --prefix "$FRONTEND_DIR" install --silent

# ---------------------------------------------------------------------------
# Write .env from environment variables
#
# In GitHub Codespaces the variables below arrive as container env vars (set
# as Codespaces secrets).  In local Dev Containers they are forwarded via
# remoteEnv in devcontainer.json.  Either way they are available at this
# point, so we write them into a .env file that FastAPI / pydantic-settings
# can pick up without any extra steps.
#
# Variables that are empty (not configured yet) are still written so the file
# is a complete template — the developer just fills in the blanks.
# ---------------------------------------------------------------------------
echo "==> Writing $ENV_FILE from environment..."

cat > "$ENV_FILE" << ENVEOF
# Auto-generated by .devcontainer/post-create.sh — edit values as needed.

# Azure OpenAI
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT:-gpt-4o}

# Eventhouse MCP (KQL / telemetry query layer)
EVENTHOUSE_MCP_ENDPOINT=${EVENTHOUSE_MCP_ENDPOINT:-}

# Azure Event Grid MQTT broker (device command dispatch)
# Hostname format: <namespace>.<region>-1.ts.eventgrid.azure.net
EVENTGRID_MQTT_HOSTNAME=${EVENTGRID_MQTT_HOSTNAME:-}
EVENTGRID_MQTT_PORT=${EVENTGRID_MQTT_PORT:-8883}

# Azure IoT Operations
INSTANCE_NAME=${INSTANCE_NAME:-}

# Application tuning
STATE_CACHE_TTL_SECONDS=${STATE_CACHE_TTL_SECONDS:-15}
ENVEOF

echo "==> Setup complete."
echo ""
echo "    Start the backend : cd src/chat-app/backend && uvicorn app.main:app --reload --port 5000"
echo "    Start the frontend: cd src/chat-app/frontend && npm run dev"
echo ""
echo "    If any .env values above are empty, edit $ENV_FILE before starting the services."
